### ISSUE TITLE
Support for .erb file

### ISSUE THREAD

**Issue by giancarlopro** [leninalbertolp/materialize-snippets-vscode#1]
Hi man, great extension.
But i would like to suggest to add native support for .erb files.

working with rails i need to change the file association to use the extension.

could you add this? or let me do?

Thanks and sorry for the bad english!

**Comment by leninalbertolp** [comment]
Hi @giancarlopro Thank you for your suggestion I just uploaded an update with support for .rb, .erb and .php file.

I hope you try and give me back the feedback

**Comment by giancarlopro** [comment]
Hi @leninalbertolp , thanks for the update!
The snippets are working well with the `.rb` files, but when i try with `.erb` they don't work.

Works with `.php` as well.

**Comment by leninalbertolp** [comment]
![screenshot_1](https://user-images.githubusercontent.com/8427648/36552973-960a3f84-17d1-11e8-8532-084dcf356767.jpg)
What do you mean when you say it doesn't work on .erb 
¿Do not charge the snippets?

**Comment by giancarlopro** [comment]
When i was on windows, only .html .rb and .php was working.
now on linux, everything works fine.

I don't know what happenned on windows, but i'm gonna test again as soon as i can to give you feedback, if you want.

Sorry for the incovinience. :+1:

**Comment by leninalbertolp** [comment]
Try reinstalling the extension, because in Windows to me it works
![screenshot_1](https://user-images.githubusercontent.com/8427648/36630998-d42c18b6-1946-11e8-81c0-c339fd1d485c.jpg)
